// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BeerColumns holds the columns for the "beer" table.
	BeerColumns = []*schema.Column{
		{Name: "idbeer", Type: field.TypeInt, Increment: true},
		{Name: "creationdatebeer", Type: field.TypeTime},
		{Name: "titlebeer", Type: field.TypeString},
		{Name: "descriptionbeer", Type: field.TypeString},
		{Name: "idmedia", Type: field.TypeInt},
	}
	// BeerTable holds the schema information for the "beer" table.
	BeerTable = &schema.Table{
		Name:       "beer",
		Columns:    BeerColumns,
		PrimaryKey: []*schema.Column{BeerColumns[0]},
	}
	// MediaColumns holds the columns for the "media" table.
	MediaColumns = []*schema.Column{
		{Name: "idmedia", Type: field.TypeInt, Increment: true},
		{Name: "creationdatemedia", Type: field.TypeTime},
		{Name: "datamedia", Type: field.TypeBytes},
		{Name: "nomemedia", Type: field.TypeString},
		{Name: "mimemedia", Type: field.TypeString},
	}
	// MediaTable holds the schema information for the "media" table.
	MediaTable = &schema.Table{
		Name:       "media",
		Columns:    MediaColumns,
		PrimaryKey: []*schema.Column{MediaColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BeerTable,
		MediaTable,
	}
)

func init() {
	BeerTable.Annotation = &entsql.Annotation{
		Table: "beer",
	}
	MediaTable.Annotation = &entsql.Annotation{
		Table: "media",
	}
}
