// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BeersColumns holds the columns for the "beers" table.
	BeersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "idbeer", Type: field.TypeInt},
		{Name: "creationdatebeer", Type: field.TypeTime},
		{Name: "titlebeer", Type: field.TypeString},
		{Name: "descriptionbeer", Type: field.TypeString},
		{Name: "idmedia", Type: field.TypeInt},
	}
	// BeersTable holds the schema information for the "beers" table.
	BeersTable = &schema.Table{
		Name:       "beers",
		Columns:    BeersColumns,
		PrimaryKey: []*schema.Column{BeersColumns[0]},
	}
	// MediaColumns holds the columns for the "media" table.
	MediaColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "idmedia", Type: field.TypeInt},
		{Name: "creationdatemedia", Type: field.TypeTime},
		{Name: "datamedia", Type: field.TypeBytes},
		{Name: "nomemedia", Type: field.TypeString},
		{Name: "mimemedia", Type: field.TypeString},
	}
	// MediaTable holds the schema information for the "media" table.
	MediaTable = &schema.Table{
		Name:       "media",
		Columns:    MediaColumns,
		PrimaryKey: []*schema.Column{MediaColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BeersTable,
		MediaTable,
	}
)

func init() {
}
