// Code generated by entc, DO NOT EDIT.

package models

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/sombriks/rosetta-beer-store/beer-store-service-go-gin-ent/service/models/beer"
)

// Beer is the model entity for the Beer schema.
type Beer struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Creationdatebeer holds the value of the "creationdatebeer" field.
	Creationdatebeer time.Time `json:"creationdatebeer,omitempty"`
	// Titlebeer holds the value of the "titlebeer" field.
	Titlebeer string `json:"titlebeer,omitempty"`
	// Descriptionbeer holds the value of the "descriptionbeer" field.
	Descriptionbeer string `json:"descriptionbeer,omitempty"`
	// Idmedia holds the value of the "idmedia" field.
	Idmedia int `json:"idmedia,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Beer) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case beer.FieldID, beer.FieldIdmedia:
			values[i] = new(sql.NullInt64)
		case beer.FieldTitlebeer, beer.FieldDescriptionbeer:
			values[i] = new(sql.NullString)
		case beer.FieldCreationdatebeer:
			values[i] = new(sql.NullTime)
		default:
			return nil, fmt.Errorf("unexpected column %q for type Beer", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Beer fields.
func (b *Beer) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case beer.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			b.ID = int(value.Int64)
		case beer.FieldCreationdatebeer:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field creationdatebeer", values[i])
			} else if value.Valid {
				b.Creationdatebeer = value.Time
			}
		case beer.FieldTitlebeer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field titlebeer", values[i])
			} else if value.Valid {
				b.Titlebeer = value.String
			}
		case beer.FieldDescriptionbeer:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field descriptionbeer", values[i])
			} else if value.Valid {
				b.Descriptionbeer = value.String
			}
		case beer.FieldIdmedia:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field idmedia", values[i])
			} else if value.Valid {
				b.Idmedia = int(value.Int64)
			}
		}
	}
	return nil
}

// Update returns a builder for updating this Beer.
// Note that you need to call Beer.Unwrap() before calling this method if this Beer
// was returned from a transaction, and the transaction was committed or rolled back.
func (b *Beer) Update() *BeerUpdateOne {
	return (&BeerClient{config: b.config}).UpdateOne(b)
}

// Unwrap unwraps the Beer entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (b *Beer) Unwrap() *Beer {
	tx, ok := b.config.driver.(*txDriver)
	if !ok {
		panic("models: Beer is not a transactional entity")
	}
	b.config.driver = tx.drv
	return b
}

// String implements the fmt.Stringer.
func (b *Beer) String() string {
	var builder strings.Builder
	builder.WriteString("Beer(")
	builder.WriteString(fmt.Sprintf("id=%v", b.ID))
	builder.WriteString(", creationdatebeer=")
	builder.WriteString(b.Creationdatebeer.Format(time.ANSIC))
	builder.WriteString(", titlebeer=")
	builder.WriteString(b.Titlebeer)
	builder.WriteString(", descriptionbeer=")
	builder.WriteString(b.Descriptionbeer)
	builder.WriteString(", idmedia=")
	builder.WriteString(fmt.Sprintf("%v", b.Idmedia))
	builder.WriteByte(')')
	return builder.String()
}

// Beers is a parsable slice of Beer.
type Beers []*Beer

func (b Beers) config(cfg config) {
	for _i := range b {
		b[_i].config = cfg
	}
}
