// Code generated by entc, DO NOT EDIT.

package models

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/sombriks/rosetta-beer-store/beer-store-service-go-gin-ent/service/models/beer"
	"github.com/sombriks/rosetta-beer-store/beer-store-service-go-gin-ent/service/models/predicate"
)

// BeerUpdate is the builder for updating Beer entities.
type BeerUpdate struct {
	config
	hooks    []Hook
	mutation *BeerMutation
}

// Where appends a list predicates to the BeerUpdate builder.
func (bu *BeerUpdate) Where(ps ...predicate.Beer) *BeerUpdate {
	bu.mutation.Where(ps...)
	return bu
}

// SetIdbeer sets the "idbeer" field.
func (bu *BeerUpdate) SetIdbeer(i int) *BeerUpdate {
	bu.mutation.ResetIdbeer()
	bu.mutation.SetIdbeer(i)
	return bu
}

// AddIdbeer adds i to the "idbeer" field.
func (bu *BeerUpdate) AddIdbeer(i int) *BeerUpdate {
	bu.mutation.AddIdbeer(i)
	return bu
}

// SetCreationdatebeer sets the "creationdatebeer" field.
func (bu *BeerUpdate) SetCreationdatebeer(t time.Time) *BeerUpdate {
	bu.mutation.SetCreationdatebeer(t)
	return bu
}

// SetTitlebeer sets the "titlebeer" field.
func (bu *BeerUpdate) SetTitlebeer(s string) *BeerUpdate {
	bu.mutation.SetTitlebeer(s)
	return bu
}

// SetDescriptionbeer sets the "descriptionbeer" field.
func (bu *BeerUpdate) SetDescriptionbeer(s string) *BeerUpdate {
	bu.mutation.SetDescriptionbeer(s)
	return bu
}

// SetIdmedia sets the "idmedia" field.
func (bu *BeerUpdate) SetIdmedia(i int) *BeerUpdate {
	bu.mutation.ResetIdmedia()
	bu.mutation.SetIdmedia(i)
	return bu
}

// AddIdmedia adds i to the "idmedia" field.
func (bu *BeerUpdate) AddIdmedia(i int) *BeerUpdate {
	bu.mutation.AddIdmedia(i)
	return bu
}

// Mutation returns the BeerMutation object of the builder.
func (bu *BeerUpdate) Mutation() *BeerMutation {
	return bu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (bu *BeerUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(bu.hooks) == 0 {
		affected, err = bu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BeerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bu.mutation = mutation
			affected, err = bu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(bu.hooks) - 1; i >= 0; i-- {
			if bu.hooks[i] == nil {
				return 0, fmt.Errorf("models: uninitialized hook (forgotten import models/runtime?)")
			}
			mut = bu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (bu *BeerUpdate) SaveX(ctx context.Context) int {
	affected, err := bu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (bu *BeerUpdate) Exec(ctx context.Context) error {
	_, err := bu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bu *BeerUpdate) ExecX(ctx context.Context) {
	if err := bu.Exec(ctx); err != nil {
		panic(err)
	}
}

func (bu *BeerUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   beer.Table,
			Columns: beer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: beer.FieldID,
			},
		},
	}
	if ps := bu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := bu.mutation.Idbeer(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: beer.FieldIdbeer,
		})
	}
	if value, ok := bu.mutation.AddedIdbeer(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: beer.FieldIdbeer,
		})
	}
	if value, ok := bu.mutation.Creationdatebeer(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: beer.FieldCreationdatebeer,
		})
	}
	if value, ok := bu.mutation.Titlebeer(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: beer.FieldTitlebeer,
		})
	}
	if value, ok := bu.mutation.Descriptionbeer(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: beer.FieldDescriptionbeer,
		})
	}
	if value, ok := bu.mutation.Idmedia(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: beer.FieldIdmedia,
		})
	}
	if value, ok := bu.mutation.AddedIdmedia(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: beer.FieldIdmedia,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, bu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{beer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return 0, err
	}
	return n, nil
}

// BeerUpdateOne is the builder for updating a single Beer entity.
type BeerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BeerMutation
}

// SetIdbeer sets the "idbeer" field.
func (buo *BeerUpdateOne) SetIdbeer(i int) *BeerUpdateOne {
	buo.mutation.ResetIdbeer()
	buo.mutation.SetIdbeer(i)
	return buo
}

// AddIdbeer adds i to the "idbeer" field.
func (buo *BeerUpdateOne) AddIdbeer(i int) *BeerUpdateOne {
	buo.mutation.AddIdbeer(i)
	return buo
}

// SetCreationdatebeer sets the "creationdatebeer" field.
func (buo *BeerUpdateOne) SetCreationdatebeer(t time.Time) *BeerUpdateOne {
	buo.mutation.SetCreationdatebeer(t)
	return buo
}

// SetTitlebeer sets the "titlebeer" field.
func (buo *BeerUpdateOne) SetTitlebeer(s string) *BeerUpdateOne {
	buo.mutation.SetTitlebeer(s)
	return buo
}

// SetDescriptionbeer sets the "descriptionbeer" field.
func (buo *BeerUpdateOne) SetDescriptionbeer(s string) *BeerUpdateOne {
	buo.mutation.SetDescriptionbeer(s)
	return buo
}

// SetIdmedia sets the "idmedia" field.
func (buo *BeerUpdateOne) SetIdmedia(i int) *BeerUpdateOne {
	buo.mutation.ResetIdmedia()
	buo.mutation.SetIdmedia(i)
	return buo
}

// AddIdmedia adds i to the "idmedia" field.
func (buo *BeerUpdateOne) AddIdmedia(i int) *BeerUpdateOne {
	buo.mutation.AddIdmedia(i)
	return buo
}

// Mutation returns the BeerMutation object of the builder.
func (buo *BeerUpdateOne) Mutation() *BeerMutation {
	return buo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (buo *BeerUpdateOne) Select(field string, fields ...string) *BeerUpdateOne {
	buo.fields = append([]string{field}, fields...)
	return buo
}

// Save executes the query and returns the updated Beer entity.
func (buo *BeerUpdateOne) Save(ctx context.Context) (*Beer, error) {
	var (
		err  error
		node *Beer
	)
	if len(buo.hooks) == 0 {
		node, err = buo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BeerMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			buo.mutation = mutation
			node, err = buo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(buo.hooks) - 1; i >= 0; i-- {
			if buo.hooks[i] == nil {
				return nil, fmt.Errorf("models: uninitialized hook (forgotten import models/runtime?)")
			}
			mut = buo.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, buo.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (buo *BeerUpdateOne) SaveX(ctx context.Context) *Beer {
	node, err := buo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (buo *BeerUpdateOne) Exec(ctx context.Context) error {
	_, err := buo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (buo *BeerUpdateOne) ExecX(ctx context.Context) {
	if err := buo.Exec(ctx); err != nil {
		panic(err)
	}
}

func (buo *BeerUpdateOne) sqlSave(ctx context.Context) (_node *Beer, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   beer.Table,
			Columns: beer.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: beer.FieldID,
			},
		},
	}
	id, ok := buo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`models: missing "Beer.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := buo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, beer.FieldID)
		for _, f := range fields {
			if !beer.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("models: invalid field %q for query", f)}
			}
			if f != beer.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := buo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := buo.mutation.Idbeer(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: beer.FieldIdbeer,
		})
	}
	if value, ok := buo.mutation.AddedIdbeer(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: beer.FieldIdbeer,
		})
	}
	if value, ok := buo.mutation.Creationdatebeer(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: beer.FieldCreationdatebeer,
		})
	}
	if value, ok := buo.mutation.Titlebeer(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: beer.FieldTitlebeer,
		})
	}
	if value, ok := buo.mutation.Descriptionbeer(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: beer.FieldDescriptionbeer,
		})
	}
	if value, ok := buo.mutation.Idmedia(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: beer.FieldIdmedia,
		})
	}
	if value, ok := buo.mutation.AddedIdmedia(); ok {
		_spec.Fields.Add = append(_spec.Fields.Add, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: beer.FieldIdmedia,
		})
	}
	_node = &Beer{config: buo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, buo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{beer.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	return _node, nil
}
