[run]
init_cmds = [
	["make", "all"],
	["beerservice"]
]
watch_all = true
watch_dirs = ["."]
watch_exts = [".go"]
ignore = [".git", "node_modules"]
ignore_files = []
build_delay = 1500
interrupt_timout = 15
graceful_kill = false
cmds = [
	["make", "build"],
	["beerservice"]
]
