// Code generated by entc, DO NOT EDIT.

package beer

const (
	// Label holds the string label denoting the beer type in the database.
	Label = "beer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldIdbeer holds the string denoting the idbeer field in the database.
	FieldIdbeer = "idbeer"
	// FieldCreationdatebeer holds the string denoting the creationdatebeer field in the database.
	FieldCreationdatebeer = "creationdatebeer"
	// FieldTitlebeer holds the string denoting the titlebeer field in the database.
	FieldTitlebeer = "titlebeer"
	// FieldDescriptionbeer holds the string denoting the descriptionbeer field in the database.
	FieldDescriptionbeer = "descriptionbeer"
	// FieldIdmedia holds the string denoting the idmedia field in the database.
	FieldIdmedia = "idmedia"
	// Table holds the table name of the beer in the database.
	Table = "beers"
)

// Columns holds all SQL columns for beer fields.
var Columns = []string{
	FieldID,
	FieldIdbeer,
	FieldCreationdatebeer,
	FieldTitlebeer,
	FieldDescriptionbeer,
	FieldIdmedia,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
