// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Beer is the predicate function for beer builders.
type Beer func(*sql.Selector)

// Media is the predicate function for media builders.
type Media func(*sql.Selector)
